### ISSUE TITLE
PDF Version

### ISSUE THREAD

**Issue by shamansir** [theseanco/howto_co34pt_liveCode#15]
Actually, it already exists :) :

[howtolivecode.pdf](https://github.com/theseanco/howto_co34pt_liveCode/files/1804486/howtolivecode.pdf)

I also have `.epub` version, if needed.

**Comment by theseanco** [comment]
this is... amazing!

Thanks so much!

I'd love a copy of the .epub too

**Comment by shamansir** [comment]
Sure, here are the `.epub` + Pages App versions as well :). 

[howtolivecode_epub.zip](https://github.com/theseanco/howto_co34pt_liveCode/files/1807452/howtolivecode_epub.zip)

[howtolivecode_pages.zip](https://github.com/theseanco/howto_co34pt_liveCode/files/1807457/howtolivecode_pages.zip)

**Comment by theseanco** [comment]
Amazing. Added them to the repo in a `Documents` folder.

I'm about to add some new articles/code/etc for the first time in a while, so the first edition is a great milestone document to have!

Thanks so much!
