### ISSUE TITLE
thisProcess.nowExecutingPath returns nil in SC VIM

### ISSUE THREAD

**Issue by datamads** [theseanco/howto_co34pt_liveCode#3]
The setup file does not work on SC Vim (only tried on Mac OSX) and returns this error:

> ERROR: Message ‘dirname’ not understood

The problem is somehow the .nowExecutingPath method. According to the docs: “This method is supported in the SuperCollider IDE, the Macintosh-only SuperCollider.app, and the scel (SuperCollider-Emacs-Lisp) environment. In other editor environments, it will return nil.”

Running just `thisProcess.nowExecutingPath` does in fact return nil. And thus the .dirname method is not understood cause it's run on `nil`. 

I'm not sure what the alternative would be yet but I'll do a little digging

**Comment by datamads** [comment]
[http://doc.sccode.org/Classes/Process.html#-nowExecutingPath](nowExecutingPath)

**Comment by theseanco** [comment]
Interesting. If you've cloned the repo would you be able to tell me if any of the `("../../Setup/Setup.scd").loadRelative` lines at the starts of examples work? In [3.4 for example](https://github.com/theseanco/howto_co34pt_liveCode/blob/master/3:%20Rhythm/3.4:%20Euclidean%20Rhythms/3.4:%20Euclidean%20Rhythms%20-%20Examples.scd)

If so you might have to specify absolute paths for everything in SCVim, which would be a shame.

**Comment by theseanco** [comment]
according to [this](https://github.com/crucialfelix/atom-supercollider/issues/49), nowExecutingPath only works in the SCIDE - so this one's above me!
