### ISSUE TITLE
Quarks.install("ddwSnippets") OSX issue

### ISSUE THREAD

**Issue by kcebul12** [theseanco/howto_co34pt_liveCode#9]
When evaluating 
```
(
Quarks.install("Bjorklund");
Quarks.install("BatLib");
Quarks.install("ddwSnippets");
)
```
I get:
Installing Bjorklund
Bjorklund installed
Installing BatLib
BatLib installed
ERROR: Quark 'ddwSnippets' not found

However, I am able to install it with `Quarks.install("https://github.com/jamshark70/ddwSnippets.git");`

**Comment by theseanco** [comment]
Hi kcebul12,

What version of SuperCollider are you using?

S

**Comment by kcebul12** [comment]
3.8

**Comment by theseanco** [comment]
Okay, I'll add a note in the tutorial

**Comment by theseanco** [comment]
Out of curiosity, is  `ddwSnippets` currently working on OSX?

**Comment by kcebul12** [comment]
I just tested it out and it appears to be fully functional for me.  I'm
really new to SC, but I was able create and "call" several snippets

**Comment by theseanco** [comment]
alright, i'll call this one closed
